export const ingredients = [
  {name: 'sliced bread', defaultMeasure: 'slice'},
  {name: 'haricot beans', defaultMeasure: 'pint'},
  {name: 'soaked haricot beans', defaultMeasure: 'pint'},
  {name: 'water', defaultMeasure: 'pint'},
  {name: 'butter', defaultMeasure: 'ounce'},
  {name: 'salt', defaultMeasure: 'salt'},
  {name: 'carrot', plural: 'carrots'},
  {name: 'large carrot', plural: 'large carrots'},
  {name: 'young carrot', plural: 'young carrots'},
  {name: 'onion', plural: 'onions'},
  {name: 'large onion', plural: 'large onions'},
  {name: 'head of celery', plural: 'heads of celery'},
  {name: 'peppercorns', defaultMeasure: 'teaspoon'},
  {name: 'mashed pototo', defaultMeasure: 'pound'},
  {name: 'soaked lentils', defaultMeasure: 'tablespoon'},
  {name: 'flour', defaultMeasure: 'ounce'},
  {name: 'shalot', plural: 'shalots'},
  {name: 'egg', plural: 'eggs'},
  {name: 'hard-boiled egg', plural: 'hard-boiled eggs'},
  {name: 'lump of sugar', plural: 'lumps of sugar'},
  {name: 'tomato sauce', defaultMeasure: 'teaspoon'},
  {name: 'pepper', defaultMeasure: 'pinch'},
  {name: 'lentils', defaultMeasure: 'pint'},
  {name: 'turnip', plural: 'turnips' },
  {name: 'potato', plural: 'potatoes'},
  {name: 'young potato', plural: 'young potatoes'},
  {name: 'minced parsley', defaultMeasure: 'tablespoon'},
  {name: 'minced watercress', defaultMeasure: 'tablespoon'},
  {name: 'tomato', plural: 'tomatoes'},
  {name: 'vinegar', defaultMeasure: 'tablespoon'},
  {name: 'green peas', defaultMeasure: 'pound'},
  {name: 'cabbage lettuce', plural: 'cabbage lettuces'},
  {name: 'chopped mint', defaultMeasure: 'tablespoon'},
  {name: 'puff pastry'},
  {name: 'pepper to taste'},
  {name: 'pear', plural: 'pears'},
  {name: 'loaf sugar', defaultMeasure: 'pound' },
  {name: 'cinnamon stick', defaultMeasure: 'inch' },
  {name: 'liquor', defaultMeasure: 'pint'},
  {name: 'breadcrumbs', defaultMeasure: 'ounce'},
  {name: 'wholemeal flour', defaultMeasure: 'ounce'},
  {name: 'white flour', defaultMeasure: 'ounce'},
  {name: 'baking powder', defaultMeasure: 'teaspoon'},
  {name: 'butter', defaultMeasure: 'ounce'},
  {name: 'sugar', defaultMeasure: 'ounce'},
  {name: 'golden syrup', defaultMeasure: 'tablespoon'},
  {name: 'vegetable marrow', plural: 'vegetable marrows'},
  {name: 'semolina', defaultMeasure: 'ounce'},
  {name: 'sweet herbs', defaultMeasure: 'teaspoon'}
]
